url: http://pytorch.org/serve
name: TorchServe
description: 'TorchServe is a flexible and easy to use tool for serving PyTorch models.'
latest_version: 1.0
baseurl:
relative_permalinks: false
timezone: America/Los_Angeles
sass:
    sass_dir: _sass # default
    style: compressed
safe: true
highlighter: rouge
markdown: kramdown
future: true
include:
    - _static
    - _modules
    - _sources
exclude:
    - node_modules
    - README.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - package.json

plugins:
  - jekyll-feed
