apiVersion: v1
kind: Pod
metadata:
  name: model-store-pod
spec:
  volumes:
    - name: pod-volume
      persistentVolumeClaim:
        claimName: model-store-claim  # Update PV Claim name
  containers:
    - name: model-store
      image: ubuntu
      command: [ "sleep" ]
      args: [ "infinity" ]
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: pod-volume
          mountPath: "/pv"
