apiVersion: v1
kind: Pod
metadata:
  name: model-store-pod
spec:
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: nfs
  containers:
    - name: model-store
      image: ubuntu
      command: [ "sleep" ]
      args: [ "infinity" ]
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: mypvc
          mountPath: "/pv"
