#frontend settings
minWorkers: 1
maxWorkers: 1
maxBatchDelay: 200
responseTimeout: 300
parallelType: "tp"
deviceType: "gpu"
torchrun:
    nproc-per-node: 4
handler:
    profile: true
    converted_ckpt_dir: "checkpoints/meta-llama/Llama-2-13b-hf/model_int8.pth"
    max_new_tokens: 50
    compile: true
    stream: false
    fx_graph_cache: True
