apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: torchserve-vs
spec:
  hosts:
    - '*'
  gateways:
    - torchserve-gw
  http:
    - match:
      - headers:
          protocol:
            exact: rest
      route:
      - destination:
          host: torchserve.default.svc.cluster.local # <ts-service-name>.<namespace>.svc.cluster.local
          port:
            number: 8080
    - match:
      - headers:
          protocol:
            exact: grpc
      route:
      - destination:
          host: torchserve.default.svc.cluster.local # <ts-service-name>.<namespace>.svc.cluster.local
          port:
            number: 7070
