name: Benchmark torchserve gpu nightly


on:
  # run every day at 2:15am
  push
  #schedule:
  #  - cron:  '15 02 * * *'

jobs:
  nightly:
    runs-on: [self-hosted, gpu]
    timeout-minutes: 1320
    steps:
      - name: Clean up previous run
        run: |
          echo "Cleaning up previous run"
          cd $RUNNER_WORKSPACE
          pwd
          cd ..
          pwd
          rm -rf _tool
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          architecture: x64
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout TorchServe
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
            sudo apt-get update -y
            sudo apt-get install -y apache2-utils
            pip install -r benchmarks/requirements-ab.txt
      - name: Benchmark gpu nightly
        run: python benchmarks/auto_benchmark.py --input benchmarks/benchmark_config_gpu.yaml --skip false
      - name: Save benchmark artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nightly gpu artifact
          path: /tmp/ts_benchmark
      - name: Download benchmark artifacts for auto validation
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          if_no_artifact_found: ignore
          path: /tmp/ts_artifacts
          name: gpu_benchmark_validation
      - name: Update benchmark artifacts for auto validation
        run: python benchmarks/utils/update_artifacts.py --output /tmp/ts_artifacts/gpu_benchmark_validation
      - name: Upload the updated benchmark artifacts for auto validation
        uses: actions/upload-artifact@v2
        with:
          name: gpu_benchmark_validation
          path: /tmp/ts_artifacts
