name: Push conda nightly

on:
  # run every day at 11:15am
  schedule:
    - cron:  '15 11 * * *'
jobs:
  nightly:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
      - run: conda --version
      - run: conda install -y conda-build
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Java Debugging
        run: |
          which javac
      - name: Checkout TorchServe
        uses: actions/checkout@v2
      - name: Install dependencies
        run: python ts_scripts/install_dependencies.py --environment=dev
      - name: conda config for auto-upload
        run: conda config --set anaconda_upload yes
      - name: Build conda package
        env:
          ANACONDA_API_TOKEN: ${{ secrets.CONDA_NIGHTLY_TOKEN }}
        run: python binaries/build.py --nightly
