name: KServe CI CPU

on:
  push:
  workflow_dispatch:
  # runs everyday  at 5:15am
  schedule:
    - cron:  '15 5 * * *'

jobs:
  kserve-ci-cpu:
    runs-on: [self-hosted, regression-test-gpu]
    steps:
      - name: Clean up previous run
        run: |
          echo "Cleaning up previous run"
          ls -la ./
          sudo rm -rf ./* || true
          sudo rm -rf ./.??* || true
          ls -la ./
      - name: Install minikube and kubectl
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          echo "/usr/local/bin" >> $GITHUB_PATH
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout TorchServe
        uses: actions/checkout@v3
      - name: Checkout kserve repo
        uses: actions/checkout@v4
        with:
          repository: kserve/kserve
          path: kserve
      - name: Test torchserve-kfs
        run: ./kubernetes/kserve/tests/scripts/test_mnist.sh
