name: Push Nightly

on:
  # run every day at 11:15am
  schedule:
    - cron:  '15 11 * * *'
jobs:
  nightly:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout TorchSeve
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          set -eux
          pip install twine
          sudo apt-get update
          python ts_scripts/install_dependencies.py --cuda=cu102 --environment=dev
          pip install -e .
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Java Debugging
        run: |
          which javac
      - name: Push nightly
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: ts_scripts/push_nightly.sh
