name: Run Regression Tests on CPU

on:
  push

concurrency:
  group: ci-cpu-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  regression-cpu:
    # creates workflows for OS: ubuntu, macOS M1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    steps:
      - name: Setup Python for M1
        if: matrix.os == 'macos-latest'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: arm64
      - name: Setup Python for all other OS
        if: matrix.os != 'macos-latest'
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: x64
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout TorchServe
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          python ts_scripts/install_dependencies.py --environment=dev
      - name: Disable MPS tests on MAC github runners
        if: matrix.os == 'macos-latest'
        run: |
          export TS_MAC_ARM64_CPU_ONLY=True
      - name: Torchserve Regression Tests
        run: |
          python test/regression_tests.py
