name: Push torchserve nightly

on:
  # run every day at 11:15am
  schedule:
    - cron:  '15 11 * * *'
jobs:
  nightly:
    # creates workflows for the 3 OS: ubuntu, macOS & windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
      - run: conda --version
      - run: conda install -y conda-build
      - name: Checkout TorchServe
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install twine
          python ts_scripts/install_dependencies.py --environment=dev
          pip install -e .
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: conda config for auto-upload
        run: conda config --set anaconda_upload yes
      - name: Build conda nightly binaries and push
        env:
          ANACONDA_API_TOKEN: ${{ secrets.CONDA_NIGHTLY_TOKEN }}
        run: python binaries/build.py --nightly
      - name: Push PyPI nightly binaries
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        # skip pushing PyPI nightly binaries for macOS & windows as the binaries have the same name
        if: matrix.os == 'ubuntu-latest'
        run: python binaries/upload.py --upload-pypi-packages --pypi-token "$PYPI_TOKEN"
